# To generate a real SECRET_KEY I used:
# python -c "import secrets; print(secrets.token_urlsafe(50))"
apiVersion: v1
kind: Secret
metadata:
  name: wger-app-secret
  namespace: wger-devops
type: Opaque
stringData:
  SECRET_KEY: "REPLACE_ME_with_a_long_random_string"
  DJANGO_DB_PASSWORD: "REPLACE_ME_use_the_same_password_as_in_wger-db-secret"
